sudo: false
language: c
compiler: clang-3.8

env:
  global:
    - VERBOSE=1
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release CFLAGS=-Werror
    - CONFIG=amalgamation CFLAGS=-Werror
    - CONFIG=release ANSI=1 CFLAGS=-Werror

addons:
  apt:
    packages:
      - clang-3.8
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test

os:
  - linux

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIG=release CFLAGS='-m32 -Werror' LDFLAGS=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      compiler: gcc
      env:
        - CONFIG=armeb CFLAGS='-DNDEBUG -g --coverage -Werror' LDFLAGS=--coverage
      before_install:
        - pip install --user cpp-coveralls 'requests[security]'
      after_success:
        - coveralls -b . --gcov $(pwd)/.deps/usr/bin/armeb-linux-gnueabihf-gcov --gcov-options '\-lp'
    - os: osx
      env: CONFIG=release
      compiler: gcc
    # lua binding builds(TODO: this is starting to get messy, lua binding should
    # probably be moved into its own repository)
    - os: linux
      compiler: gcc
      env: CONFIG=lua-5.1-binding  # set for the description in travis UI
      addons:
        apt:
          packages:
            - valgrind
      script:
        - make config=amalgamation
        - if ! make MPACK_LUA_VERSION=5.1.5 -C binding/lua ci-test; then cat binding/lua/valgrind.log; exit 1; fi
    - os: linux
      compiler: gcc
      env: CONFIG=lua-5.2-binding  # set for the description in travis UI
      addons:
        apt:
          packages:
            - valgrind
      script:
        - make config=amalgamation
        - if ! make MPACK_LUA_VERSION=5.2.4 -C binding/lua ci-test; then cat binding/lua/valgrind.log; exit 1; fi
    - os: linux
      compiler: gcc
      env: CONFIG=lua-5.3-binding  # set for the description in travis UI
      addons:
        apt:
          packages:
            - valgrind
      script:
        - make config=amalgamation
        - if ! make MPACK_LUA_VERSION=5.3.3 -C binding/lua ci-test; then cat binding/lua/valgrind.log; exit 1; fi
    - os: linux
      env: CONFIG=python2-binding
      script:
        - cd binding/python && ./ci.sh
    - os: linux
      env: CONFIG=python3-binding
      script:
        - cd binding/python && ./ci.sh

script:
  make config=${CONFIG} test

cache:
  directories:
    - .deps/usr
    - binding/lua/.deps/5.1.5/usr
    - binding/lua/.deps/5.2.4/usr
    - binding/lua/.deps/5.3.3/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
