sudo: false
language: c
compiler: clang

env:
  global:
    - VERBOSE=1
  matrix:
    - CONFIG=asan
    - CONFIG=msan
    - CONFIG=ubsan
    - CONFIG=debug
    - CONFIG=release CFLAGS=-Werror
    - CONFIG=amalgamation CFLAGS=-Werror
    - CONFIG=release ANSI=1 CFLAGS=-Werror

os:
  - linux

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIG=release CFLAGS='-m32 -Werror' LDFLAGS=-m32
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      compiler: gcc
      env:
        - CONFIG=armeb CFLAGS='-DNDEBUG -g --coverage -Werror' LDFLAGS=--coverage
      before_install:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls -b . --gcov $(pwd)/.deps/usr/bin/armeb-linux-gnueabihf-gcov --gcov-options '\-lp'
    - os: osx
      env: CONFIG=release
      compiler: gcc
    - os: linux
      compiler: gcc
      env: CONFIG=lua-binding  # set for the description in travis UI
      addons:
        apt:
          packages:
            - valgrind
      script:
        - make config=amalgamation
        - if ! make -C binding/lua valgrind; then cat binding/lua/valgrind.log; exit 1; fi

script:
  make config=${CONFIG} test

cache:
  directories:
    - .deps/usr
    - binding/lua/.deps/5.1.5/usr

after_failure:
  cat asan.* ubsan.* msan.* || true
